<?php

  if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array (
  	'key' => 'group_59c29d5879b66',
  	'title' => 'Clock In Page',
  	'fields' => array (
  		array (
  			'key' => 'field_59c29d6a3d5c8',
  			'label' => 'Logged in Employee',
  			'name' => 'logged_in_employee',
  			'type' => 'text',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'prepend' => '',
  			'append' => '',
  			'maxlength' => '',
  		),
  		array (
  			'key' => 'field_59c2cef84b188',
  			'label' => 'Logged in Employee PIN',
  			'name' => 'logged_in_employee_pin',
  			'type' => 'text',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'prepend' => '',
  			'append' => '',
  			'maxlength' => '',
  		),
  		array (
  			'key' => 'field_59c2f8caeb53e',
  			'label' => 'Logged in Employee Index',
  			'name' => 'logged_in_employee_index',
  			'type' => 'number',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'prepend' => '',
  			'append' => '',
  			'min' => '',
  			'max' => '',
  			'step' => '',
  		),
  		array (
  			'key' => 'field_59c2db5a813bf',
  			'label' => 'Clocked in Employees',
  			'name' => 'clocked_in_employees',
  			'type' => 'repeater',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'collapsed' => '',
  			'min' => 0,
  			'max' => 0,
  			'layout' => 'table',
  			'button_label' => '',
  			'sub_fields' => array (
  				array (
  					'key' => 'field_59c2dbbb813c0',
  					'label' => 'Clocked in Employee',
  					'name' => 'clocked_in_employee',
  					'type' => 'text',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array (
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'default_value' => '',
  					'placeholder' => '',
  					'prepend' => '',
  					'append' => '',
  					'maxlength' => '',
  				),
  				array (
  					'key' => 'field_59c2dbcf813c1',
  					'label' => 'Clocked in Employee PIN',
  					'name' => 'clocked_in_employee_pin',
  					'type' => 'text',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array (
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'default_value' => '',
  					'placeholder' => '',
  					'prepend' => '',
  					'append' => '',
  					'maxlength' => '',
  				),
  				array (
  					'key' => 'field_59c2dbe0813c2',
  					'label' => 'Current Timestamp ID',
  					'name' => 'current_timestamp_id',
  					'type' => 'text',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array (
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'default_value' => '',
  					'placeholder' => '',
  					'prepend' => '',
  					'append' => '',
  					'maxlength' => '',
  				),
  				array (
  					'key' => 'field_59c2e03f813c4',
  					'label' => 'Current Session Clock In Time',
  					'name' => 'current_clock_in_time',
  					'type' => 'time_picker',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array (
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'display_format' => 'g:i a',
  					'return_format' => 'g:i a',
  				),
  			),
  		),
  	),
  	'location' => array (
  		array (
  			array (
  				'param' => 'page',
  				'operator' => '==',
  				'value' => '11',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'default',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 1,
  	'description' => '',
  ));

  acf_add_local_field_group(array (
  	'key' => 'group_59c28b11e63db',
  	'title' => 'Employees',
  	'fields' => array (
  		array (
  			'key' => 'field_59c28b420a57e',
  			'label' => 'Employees',
  			'name' => 'employees',
  			'type' => 'repeater',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'collapsed' => 'field_59c28c800a57f',
  			'min' => 0,
  			'max' => 0,
  			'layout' => 'row',
  			'button_label' => '',
  			'sub_fields' => array (
  				array (
  					'key' => 'field_59c28c800a57f',
  					'label' => 'Employee Name',
  					'name' => 'employee_name',
  					'type' => 'text',
  					'instructions' => '',
  					'required' => 1,
  					'conditional_logic' => 0,
  					'wrapper' => array (
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'default_value' => '',
  					'placeholder' => '',
  					'prepend' => '',
  					'append' => '',
  					'maxlength' => '',
  				),
  				array (
  					'key' => 'field_59c28c970a580',
  					'label' => 'Employee Pin',
  					'name' => 'employee_pin',
  					'type' => 'number',
  					'instructions' => '',
  					'required' => 1,
  					'conditional_logic' => 0,
  					'wrapper' => array (
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'default_value' => '',
  					'placeholder' => '',
  					'prepend' => '',
  					'append' => '',
  					'min' => 1000,
  					'max' => 9999,
  					'step' => '',
  				),
  				array (
  					'key' => 'field_59c2ae4516483',
  					'label' => 'Clocked In?',
  					'name' => 'is_clocked_in',
  					'type' => 'true_false',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array (
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'message' => '',
  					'default_value' => 0,
  					'ui' => 0,
  					'ui_on_text' => '',
  					'ui_off_text' => '',
  				),
  				array (
  					'key' => 'field_59c29122851b5',
  					'label' => 'Timesheet',
  					'name' => 'timesheet',
  					'type' => 'repeater',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array (
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'collapsed' => 'field_59c29136851b6',
  					'min' => 0,
  					'max' => 0,
  					'layout' => 'table',
  					'button_label' => 'Add Time',
  					'sub_fields' => array (
  						array (
  							'key' => 'field_59c29136851b6',
  							'label' => 'Date',
  							'name' => 'date',
  							'type' => 'date_picker',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array (
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'display_format' => 'm/d/Y',
  							'return_format' => 'm/d/Y',
  							'first_day' => 1,
  						),
  						array (
  							'key' => 'field_59c2916b851b7',
  							'label' => 'Clocked In',
  							'name' => 'clocked_in',
  							'type' => 'time_picker',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array (
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'display_format' => 'g:i a',
  							'return_format' => 'g:i a',
  						),
  						array (
  							'key' => 'field_59c29194851b8',
  							'label' => 'Clocked Out',
  							'name' => 'clocked_out',
  							'type' => 'time_picker',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array (
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'display_format' => 'g:i a',
  							'return_format' => 'g:i a',
  						),
  						array (
  							'key' => 'field_59c2ce8a9718a',
  							'label' => 'ID',
  							'name' => 'time_id',
  							'type' => 'text',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array (
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'placeholder' => '',
  							'prepend' => '',
  							'append' => '',
  							'maxlength' => '',
  						),
  					),
  				),
  			),
  		),
  	),
  	'location' => array (
  		array (
  			array (
  				'param' => 'options_page',
  				'operator' => '==',
  				'value' => 'acf-options-addedit-employees',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'default',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 1,
  	'description' => '',
  ));

  endif;

?>
